export const NODE_DOUBLE_TAP_MS = 700
export const SELECTED_PULSE_INTERVAL_MS = 520
export const DEFAULT_THRESHOLD = '0.10'

export const MIN_ZOOM_LABELS_ALL = 0.85
export const MIN_ZOOM_LABELS_PERSON = 1.25

export const DEFAULT_LAYOUT_SPACING = 2.2
export const DEFAULT_FOCUS_DEPTH: 1 | 2 = 1

export const HISTOGRAM_BINS_COUNT = 20
export const PARTICIPANT_SUGGESTIONS_LIMIT = 20
